# Generated by Django 4.2.16 on 2024-11-06 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminStaff',
            fields=[
                ('admin_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, max_length=24, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'admin_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdmissionStaff',
            fields=[
                ('admission_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, max_length=24, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'admission_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuidanceStaff',
            fields=[
                ('guidance_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, max_length=24, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'guidance_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegistrarStaff',
            fields=[
                ('registrar_staff_id', models.IntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, max_length=24, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'registrar_staff',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('passcode', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'user_account',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('event', models.DateField(null=True)),
            ],
            options={
                'db_table': 'annoucement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacultyStaff',
            fields=[
                ('faculty_staff_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=24, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'faculty_staff',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_lrn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=24)),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=24, null=True)),
                ('birth_date', models.DateField()),
                ('birth_place', models.CharField(blank=True, max_length=200, null=True)),
                ('religion', models.CharField(blank=True, max_length=24, null=True)),
                ('civil_status', models.CharField(blank=True, max_length=10, null=True)),
                ('contact', models.BigIntegerField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.facultystaff')),
            ],
            options={
                'db_table': 'student_profile',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='section',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.section'),
        ),
    ]
