# Generated by Django 4.2.16 on 2024-11-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0002_studentprofile_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
    ]
