# Generated by Django 4.2.16 on 2024-10-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0002_adminstaff_admissionstaff_annoucement_facultystaff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_lrn',
            field=models.IntegerField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
