# Generated by Django 5.1.3 on 2024-11-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0003_subject_facultystaff_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='subject',
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
