# Generated by Django 4.2.16 on 2024-11-06 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0004_alter_studentprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystaff',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Status', max_length=10, null=True),
        ),
    ]
