# Generated by Django 4.2.16 on 2024-10-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0004_alter_studentprofile_student_lrn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='student_lrn',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
