# Generated by Django 4.2.16 on 2024-11-06 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0005_alter_facultystaff_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystaff',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.section'),
        ),
    ]
