# Generated by Django 4.2.16 on 2024-10-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0006_studentprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='civil_status',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
