# Generated by Django 4.2.16 on 2024-10-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0007_alter_studentprofile_civil_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='section',
            field=models.CharField(max_length=24),
        ),
    ]
