# Generated by Django 4.2.16 on 2024-10-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0008_alter_studentprofile_section'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultystaff',
            options={'managed': True},
        ),
    ]
