# Generated by Django 4.2.16 on 2024-10-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0009_alter_facultystaff_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystaff',
            name='section',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
