# Generated by Django 4.2.16 on 2024-11-12 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0010_delete_attendance_section_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.level'),
        ),
    ]
