# Generated by Django 4.2.16 on 2024-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0010_facultystaff_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystaff',
            name='contact',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facultystaff',
            name='faculty_staff_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
