# Generated by Django 4.2.16 on 2024-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0011_alter_facultystaff_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystaff',
            name='section',
            field=models.CharField(max_length=24),
        ),
    ]
