# Generated by Django 4.2.16 on 2024-11-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0011_alter_section_level'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
