# Generated by Django 4.2.16 on 2024-11-12 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0012_delete_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystaff',
            name='students',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.studentprofile'),
        ),
    ]
