# Generated by Django 4.2.16 on 2024-10-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0013_genesis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genesis',
        ),
    ]
