# Generated by Django 4.2.16 on 2024-11-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0013_facultystaff_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultystaff',
            name='students',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='adviser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_staff.facultystaff'),
        ),
    ]
