# Generated by Django 4.2.16 on 2024-11-12 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0014_remove_facultystaff_students_studentprofile_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystaff',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='birth_place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='facultystaff',
            name='religion',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
