# Generated by Django 4.2.16 on 2024-10-29 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0014_delete_genesis'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annoucement',
            options={'managed': True},
        ),
    ]
