# Generated by Django 4.2.16 on 2024-10-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0015_alter_annoucement_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='annoucement',
            name='event',
            field=models.DateField(blank=True, null=True),
        ),
    ]
