# Generated by Django 4.2.16 on 2024-11-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0015_facultystaff_birth_date_facultystaff_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultystaff',
            name='civil_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], default='Status', max_length=10, null=True),
        ),
    ]
