# Generated by Django 4.2.16 on 2024-10-29 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0016_annoucement_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoucement',
            name='event',
            field=models.DateField(),
        ),
    ]
