# Generated by Django 4.2.16 on 2024-10-29 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0018_level_section_alter_annoucement_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='level_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20)),
                ('section_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='level',
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
