# Generated by Django 4.2.16 on 2024-10-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0020_level_section_delete_level_section'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Annoucement',
            new_name='Announcement',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='annoucement_id',
            new_name='announcement_id',
        ),
    ]
