# Generated by Django 4.2.16 on 2024-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0021_rename_annoucement_announcement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('1', 'male'), ('2', 'female')], default='gender', max_length=24, null=True),
        ),
    ]
