# Generated by Django 4.2.16 on 2024-10-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0023_alter_studentprofile_civil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='civil_status',
            field=models.CharField(choices=[('single', 'single'), ('married', 'married'), ('separated', 'separated'), ('divorced', 'divorced'), ('widowed', 'widowed')], default='status', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], default='gender', max_length=24, null=True),
        ),
    ]
