# Generated by Django 4.2.16 on 2024-10-31 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_staff', '0025_alter_studentprofile_civil_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultystaff',
            name='section',
            field=models.CharField(choices=[('Genesis', 'Genesis'), ('Judges', 'Judges'), ('Exodus', 'Exodus'), ('Ezra', 'Ezra'), ('Psalm', 'Psalm'), ('Zachariah', 'Zachariah'), ('Proverbs', 'Proverbs')], default='section', max_length=24),
        ),
    ]
